/* The following code was generated by JFlex 1.4.3 on 07/01/25 14:38 */

package analizara;
import static analizara.Token.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 07/01/25 14:38 from the specification file
 * <tt>/Users/david/Desktop/Universidad/SEMESTRE_5/LYA/compilador/analizara/src/analizara/lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\35\2\0\1\3\22\0\1\3\1\61\1\62\2\0"+
    "\1\45\1\0\1\60\1\37\1\36\1\43\1\41\1\55\1\42\1\56"+
    "\1\34\12\2\1\57\1\46\1\47\1\40\1\50\2\0\2\1\1\22"+
    "\17\1\1\26\7\1\1\53\1\0\1\54\1\44\1\1\1\0\1\15"+
    "\1\6\1\11\1\16\1\20\1\24\1\21\1\27\1\10\1\1\1\31"+
    "\1\7\1\30\1\23\1\12\1\4\1\1\1\13\1\25\1\17\1\5"+
    "\1\14\1\1\1\32\1\33\1\1\1\51\1\0\1\52\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\4\2\1\5\13\2"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\1\1\34"+
    "\26\2\1\35\3\2\1\4\1\0\1\36\1\37\1\40"+
    "\1\41\36\2\1\0\14\2\1\42\12\2\1\43\4\2"+
    "\1\44\3\2\1\3\4\2\1\45\5\2\1\46\4\2"+
    "\1\47\1\2\1\50\5\2\1\51\1\2\1\52\1\53"+
    "\1\54\1\55\14\2\1\56\3\2\1\57\2\2\1\60"+
    "\2\2\1\61\1\62\11\2\1\63\7\2\1\64\1\2"+
    "\1\65\1\2\1\66\1\67\1\70\1\71\2\2\1\72"+
    "\1\73\1\74\1\75\1\76\1\77\1\2\1\100\1\2"+
    "\1\101\1\102";

  private static int [] zzUnpackAction() {
    int [] result = new int[232];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\231\0\63\0\314\0\377\0\u0132"+
    "\0\u0165\0\u0198\0\u01cb\0\u01fe\0\u0231\0\u0264\0\u0297\0\u02ca"+
    "\0\u02fd\0\u0330\0\u0363\0\u0396\0\u03c9\0\146\0\u03fc\0\63"+
    "\0\63\0\u042f\0\u0462\0\63\0\63\0\63\0\63\0\63"+
    "\0\63\0\u0495\0\u04c8\0\63\0\63\0\63\0\63\0\63"+
    "\0\63\0\63\0\63\0\u04fb\0\63\0\u052e\0\u0561\0\u0594"+
    "\0\u05c7\0\u05fa\0\u062d\0\u0660\0\u0693\0\u06c6\0\u06f9\0\u072c"+
    "\0\u075f\0\u0792\0\u07c5\0\u07f8\0\u082b\0\u085e\0\u0891\0\u08c4"+
    "\0\u08f7\0\u092a\0\u095d\0\146\0\u0990\0\u09c3\0\u09f6\0\u0a29"+
    "\0\u0a5c\0\63\0\63\0\63\0\63\0\u0a8f\0\u0ac2\0\u0af5"+
    "\0\u0b28\0\u0b5b\0\u0b8e\0\u0bc1\0\u0bf4\0\u0c27\0\u0c5a\0\u0c8d"+
    "\0\u0cc0\0\u0cf3\0\u0d26\0\u0d59\0\u0d8c\0\u0dbf\0\u0df2\0\u0e25"+
    "\0\u0e58\0\u0e8b\0\u0ebe\0\u0ef1\0\u0f24\0\u0f57\0\u0f8a\0\u0fbd"+
    "\0\u0ff0\0\u1023\0\u1056\0\u1089\0\u10bc\0\u10ef\0\u1122\0\u1155"+
    "\0\u1188\0\u11bb\0\u11ee\0\u1221\0\u1254\0\u1287\0\u12ba\0\u12ed"+
    "\0\146\0\u1320\0\u1353\0\u1386\0\u13b9\0\u13ec\0\u141f\0\u1452"+
    "\0\u1485\0\u14b8\0\u14eb\0\146\0\u151e\0\u1551\0\u1584\0\u15b7"+
    "\0\146\0\u15ea\0\u161d\0\u1650\0\63\0\u1683\0\u16b6\0\u16e9"+
    "\0\u171c\0\146\0\u174f\0\u1782\0\u17b5\0\u17e8\0\u181b\0\146"+
    "\0\u184e\0\u1881\0\u18b4\0\u18e7\0\146\0\u191a\0\146\0\u194d"+
    "\0\u1980\0\u19b3\0\u19e6\0\u1a19\0\146\0\u1a4c\0\146\0\146"+
    "\0\146\0\146\0\u1a7f\0\u1ab2\0\u1ae5\0\u1b18\0\u1b4b\0\u1b7e"+
    "\0\u1bb1\0\u1be4\0\u1c17\0\u1c4a\0\u1c7d\0\u1cb0\0\146\0\u1ce3"+
    "\0\u1d16\0\u1d49\0\146\0\u1d7c\0\u1daf\0\146\0\u1de2\0\u1e15"+
    "\0\146\0\146\0\u1e48\0\u1e7b\0\u1eae\0\u1ee1\0\u1f14\0\u1f47"+
    "\0\u1f7a\0\u1fad\0\u1fe0\0\146\0\u2013\0\u2046\0\u2079\0\u20ac"+
    "\0\u20df\0\u2112\0\u2145\0\146\0\u2178\0\146\0\u21ab\0\146"+
    "\0\146\0\146\0\146\0\u21de\0\u2211\0\146\0\146\0\146"+
    "\0\146\0\146\0\146\0\u2244\0\146\0\u2277\0\146\0\146";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[232];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\3\1\7\1\3"+
    "\1\10\1\11\1\12\1\13\1\14\1\3\1\15\1\3"+
    "\1\16\1\3\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\2\3\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\64\0\2\3\1\0\30\3\31\0\1\4"+
    "\61\0\2\3\1\0\1\3\1\56\5\3\1\57\20\3"+
    "\30\0\2\3\1\0\6\3\1\60\1\61\20\3\30\0"+
    "\2\3\1\0\17\3\1\62\4\3\1\63\3\3\30\0"+
    "\2\3\1\0\3\3\1\64\5\3\1\65\16\3\30\0"+
    "\2\3\1\0\1\66\27\3\30\0\2\3\1\0\14\3"+
    "\1\67\13\3\30\0\2\3\1\0\11\3\1\70\2\3"+
    "\1\71\13\3\30\0\2\3\1\0\6\3\1\72\5\3"+
    "\1\73\13\3\30\0\2\3\1\0\17\3\1\74\1\3"+
    "\1\75\4\3\1\76\1\3\30\0\2\3\1\0\11\3"+
    "\1\77\16\3\30\0\2\3\1\0\1\3\1\100\26\3"+
    "\30\0\2\3\1\0\3\3\1\101\1\102\4\3\1\103"+
    "\16\3\30\0\2\3\1\0\4\3\1\104\23\3\30\0"+
    "\2\3\1\0\4\3\1\105\23\3\30\0\2\3\1\0"+
    "\11\3\1\106\16\3\30\0\2\3\1\0\4\3\1\107"+
    "\23\3\63\0\1\110\70\0\1\111\60\0\1\112\62\0"+
    "\1\113\62\0\1\114\62\0\1\115\23\0\2\3\1\0"+
    "\2\3\1\116\25\3\30\0\2\3\1\0\4\3\1\117"+
    "\1\3\1\120\21\3\30\0\2\3\1\0\6\3\1\121"+
    "\21\3\30\0\2\3\1\0\14\3\1\122\13\3\30\0"+
    "\2\3\1\0\13\3\1\123\14\3\30\0\2\3\1\0"+
    "\1\124\27\3\30\0\2\3\1\0\11\3\1\125\16\3"+
    "\30\0\2\3\1\0\1\126\6\3\1\127\11\3\1\130"+
    "\6\3\30\0\2\3\1\0\5\3\1\131\22\3\30\0"+
    "\2\3\1\0\13\3\1\132\14\3\30\0\2\3\1\0"+
    "\5\3\1\133\22\3\30\0\2\3\1\0\7\3\1\134"+
    "\20\3\30\0\2\3\1\0\2\3\1\135\25\3\30\0"+
    "\2\3\1\0\6\3\1\136\21\3\30\0\2\3\1\0"+
    "\13\3\1\137\14\3\30\0\2\3\1\0\13\3\1\140"+
    "\14\3\30\0\2\3\1\0\13\3\1\141\14\3\30\0"+
    "\2\3\1\0\12\3\1\142\15\3\30\0\2\3\1\0"+
    "\3\3\1\143\10\3\1\144\13\3\30\0\2\3\1\0"+
    "\6\3\1\145\21\3\30\0\2\3\1\0\17\3\1\146"+
    "\10\3\30\0\2\3\1\0\3\3\1\147\24\3\30\0"+
    "\2\3\1\0\17\3\1\150\10\3\30\0\2\3\1\0"+
    "\5\3\1\151\13\3\1\152\6\3\30\0\2\3\1\0"+
    "\14\3\1\153\13\3\27\0\35\110\1\0\25\110\2\0"+
    "\1\154\61\0\2\3\1\0\3\3\1\155\24\3\30\0"+
    "\2\3\1\0\10\3\1\156\17\3\30\0\2\3\1\0"+
    "\13\3\1\157\14\3\30\0\2\3\1\0\3\3\1\160"+
    "\24\3\30\0\2\3\1\0\11\3\1\161\16\3\30\0"+
    "\2\3\1\0\14\3\1\162\13\3\30\0\2\3\1\0"+
    "\3\3\1\163\2\3\1\164\1\165\20\3\30\0\2\3"+
    "\1\0\21\3\1\166\6\3\30\0\2\3\1\0\13\3"+
    "\1\167\14\3\30\0\2\3\1\0\11\3\1\170\16\3"+
    "\30\0\2\3\1\0\6\3\1\171\21\3\30\0\2\3"+
    "\1\0\4\3\1\172\23\3\30\0\2\3\1\0\6\3"+
    "\1\173\21\3\30\0\2\3\1\0\4\3\1\174\23\3"+
    "\30\0\2\3\1\0\12\3\1\175\15\3\30\0\2\3"+
    "\1\0\3\3\1\176\24\3\30\0\2\3\1\0\13\3"+
    "\1\177\14\3\30\0\2\3\1\0\14\3\1\200\13\3"+
    "\30\0\2\3\1\0\11\3\1\201\16\3\30\0\2\3"+
    "\1\0\4\3\1\202\23\3\30\0\2\3\1\0\14\3"+
    "\1\203\13\3\30\0\2\3\1\0\6\3\1\204\21\3"+
    "\30\0\2\3\1\0\10\3\1\205\17\3\30\0\2\3"+
    "\1\0\13\3\1\206\14\3\30\0\2\3\1\0\11\3"+
    "\1\207\16\3\30\0\2\3\1\0\21\3\1\210\6\3"+
    "\30\0\2\3\1\0\6\3\1\211\21\3\30\0\2\3"+
    "\1\0\14\3\1\212\13\3\30\0\2\3\1\0\13\3"+
    "\1\213\14\3\30\0\2\3\1\0\17\3\1\214\10\3"+
    "\31\0\1\154\33\0\1\215\25\0\2\3\1\0\4\3"+
    "\1\216\23\3\30\0\2\3\1\0\11\3\1\217\16\3"+
    "\30\0\2\3\1\0\14\3\1\220\13\3\30\0\2\3"+
    "\1\0\14\3\1\221\13\3\30\0\2\3\1\0\25\3"+
    "\1\222\2\3\30\0\2\3\1\0\7\3\1\223\7\3"+
    "\1\224\10\3\30\0\2\3\1\0\14\3\1\225\13\3"+
    "\30\0\2\3\1\0\7\3\1\226\20\3\30\0\2\3"+
    "\1\0\4\3\1\227\23\3\30\0\2\3\1\0\14\3"+
    "\1\230\13\3\30\0\2\3\1\0\1\3\1\231\26\3"+
    "\30\0\2\3\1\0\5\3\1\232\22\3\30\0\2\3"+
    "\1\0\6\3\1\233\21\3\30\0\2\3\1\0\7\3"+
    "\1\234\20\3\30\0\2\3\1\0\6\3\1\235\21\3"+
    "\30\0\2\3\1\0\11\3\1\236\16\3\30\0\2\3"+
    "\1\0\14\3\1\237\13\3\30\0\2\3\1\0\7\3"+
    "\1\240\20\3\30\0\2\3\1\0\7\3\1\241\20\3"+
    "\30\0\2\3\1\0\13\3\1\242\14\3\30\0\2\3"+
    "\1\0\14\3\1\243\13\3\30\0\2\3\1\0\17\3"+
    "\1\244\10\3\30\0\2\3\1\0\6\3\1\245\21\3"+
    "\30\0\2\3\1\0\11\3\1\246\16\3\30\0\2\3"+
    "\1\0\3\3\1\247\24\3\30\0\2\3\1\0\6\3"+
    "\1\250\21\3\30\0\2\3\1\0\7\3\1\251\20\3"+
    "\30\0\2\3\1\0\11\3\1\252\16\3\30\0\2\3"+
    "\1\0\13\3\1\253\14\3\30\0\2\3\1\0\5\3"+
    "\1\254\22\3\30\0\2\3\1\0\12\3\1\255\15\3"+
    "\30\0\2\3\1\0\15\3\1\256\12\3\30\0\2\3"+
    "\1\0\11\3\1\257\16\3\30\0\2\3\1\0\20\3"+
    "\1\260\7\3\30\0\2\3\1\0\13\3\1\261\14\3"+
    "\30\0\2\3\1\0\24\3\1\262\3\3\30\0\2\3"+
    "\1\0\13\3\1\263\14\3\30\0\2\3\1\0\24\3"+
    "\1\264\3\3\30\0\2\3\1\0\7\3\1\265\20\3"+
    "\30\0\2\3\1\0\13\3\1\266\14\3\30\0\2\3"+
    "\1\0\17\3\1\267\10\3\30\0\2\3\1\0\17\3"+
    "\1\270\10\3\30\0\2\3\1\0\12\3\1\271\15\3"+
    "\30\0\2\3\1\0\6\3\1\272\21\3\30\0\2\3"+
    "\1\0\6\3\1\273\21\3\30\0\2\3\1\0\4\3"+
    "\1\274\23\3\30\0\2\3\1\0\17\3\1\275\10\3"+
    "\30\0\2\3\1\0\11\3\1\276\16\3\30\0\2\3"+
    "\1\0\17\3\1\277\10\3\30\0\2\3\1\0\7\3"+
    "\1\300\20\3\30\0\2\3\1\0\6\3\1\301\21\3"+
    "\30\0\2\3\1\0\6\3\1\302\21\3\30\0\2\3"+
    "\1\0\4\3\1\303\23\3\30\0\2\3\1\0\17\3"+
    "\1\304\10\3\30\0\2\3\1\0\11\3\1\305\16\3"+
    "\30\0\2\3\1\0\11\3\1\306\16\3\30\0\2\3"+
    "\1\0\14\3\1\307\13\3\30\0\2\3\1\0\11\3"+
    "\1\310\16\3\30\0\2\3\1\0\4\3\1\311\23\3"+
    "\30\0\2\3\1\0\11\3\1\312\16\3\30\0\2\3"+
    "\1\0\14\3\1\313\13\3\30\0\2\3\1\0\6\3"+
    "\1\314\21\3\30\0\2\3\1\0\14\3\1\315\13\3"+
    "\30\0\2\3\1\0\24\3\1\316\3\3\30\0\2\3"+
    "\1\0\5\3\1\317\22\3\30\0\2\3\1\0\12\3"+
    "\1\320\15\3\30\0\2\3\1\0\13\3\1\321\14\3"+
    "\30\0\2\3\1\0\11\3\1\322\16\3\30\0\2\3"+
    "\1\0\12\3\1\323\15\3\30\0\2\3\1\0\6\3"+
    "\1\324\21\3\30\0\2\3\1\0\5\3\1\325\22\3"+
    "\30\0\2\3\1\0\7\3\1\326\20\3\30\0\2\3"+
    "\1\0\17\3\1\327\10\3\30\0\2\3\1\0\7\3"+
    "\1\330\20\3\30\0\2\3\1\0\7\3\1\331\20\3"+
    "\30\0\2\3\1\0\7\3\1\332\20\3\30\0\2\3"+
    "\1\0\7\3\1\333\20\3\30\0\2\3\1\0\7\3"+
    "\1\334\20\3\30\0\2\3\1\0\6\3\1\335\21\3"+
    "\30\0\2\3\1\0\6\3\1\336\21\3\30\0\2\3"+
    "\1\0\14\3\1\337\13\3\30\0\2\3\1\0\14\3"+
    "\1\340\13\3\30\0\2\3\1\0\21\3\1\341\6\3"+
    "\30\0\2\3\1\0\6\3\1\342\21\3\30\0\2\3"+
    "\1\0\14\3\1\343\13\3\30\0\2\3\1\0\13\3"+
    "\1\344\14\3\30\0\2\3\1\0\6\3\1\345\21\3"+
    "\30\0\2\3\1\0\12\3\1\346\15\3\30\0\2\3"+
    "\1\0\11\3\1\347\16\3\30\0\2\3\1\0\6\3"+
    "\1\350\21\3\27\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8874];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\22\1\2\11\2\1\6\11"+
    "\2\1\10\11\1\1\1\11\33\1\1\0\4\11\36\1"+
    "\1\0\40\1\1\11\133\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[232];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
public String tipo;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 138) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 36: 
          { tipo=yytext(); return Sino;
          }
        case 67: break;
        case 66: 
          { tipo=yytext(); return De_otro_modo;
          }
        case 68: break;
        case 59: 
          { tipo=yytext(); return Extiende;
          }
        case 69: break;
        case 55: 
          { tipo=yytext(); return Metodo_imprimir;
          }
        case 70: break;
        case 1: 
          { return Error;
          }
        case 71: break;
        case 37: 
          { tipo=yytext(); return Break;
          }
        case 72: break;
        case 2: 
          { tipo=yytext(); return Identificador;
          }
        case 73: break;
        case 18: 
          { tipo=yytext(); return Menor;
          }
        case 74: break;
        case 31: 
          { tipo=yytext(); return Menor_igual;
          }
        case 75: break;
        case 61: 
          { tipo=yytext(); return Mientras;
          }
        case 76: break;
        case 42: 
          { tipo=yytext(); return Final_2;
          }
        case 77: break;
        case 58: 
          { tipo=yytext(); return Estatico;
          }
        case 78: break;
        case 51: 
          { tipo=yytext(); return Retorno;
          }
        case 79: break;
        case 49: 
          { tipo=yytext(); return Publico;
          }
        case 80: break;
        case 27: 
          { tipo=yytext(); return Comilla_simple;
          }
        case 81: break;
        case 29: 
          { tipo=yytext(); return Si;
          }
        case 82: break;
        case 8: 
          { tipo=yytext(); return Linea;
          }
        case 83: break;
        case 62: 
          { tipo=yytext(); return Protegido;
          }
        case 84: break;
        case 5: 
          { tipo=yytext(); return O;
          }
        case 85: break;
        case 26: 
          { tipo=yytext(); return Dos_puntos;
          }
        case 86: break;
        case 47: 
          { tipo=yytext(); return Entero;
          }
        case 87: break;
        case 44: 
          { tipo=yytext(); return Hacer;
          }
        case 88: break;
        case 46: 
          { tipo=yytext(); return Opcion;
          }
        case 89: break;
        case 43: 
          { tipo=yytext(); return Falso;
          }
        case 90: break;
        case 14: 
          { tipo=yytext(); return Multiplicacion;
          }
        case 91: break;
        case 11: 
          { tipo=yytext(); return Asignar;
          }
        case 92: break;
        case 7: 
          { tipo=yytext(); return Division;
          }
        case 93: break;
        case 40: 
          { tipo=yytext(); return Doble;
          }
        case 94: break;
        case 56: 
          { tipo=yytext(); return Capturar;
          }
        case 95: break;
        case 60: 
          { tipo=yytext(); return Flotante;
          }
        case 96: break;
        case 16: 
          { tipo=yytext(); return Modulo;
          }
        case 97: break;
        case 38: 
          { tipo=yytext(); return Clase;
          }
        case 98: break;
        case 28: 
          { tipo=yytext(); return Comillas;
          }
        case 99: break;
        case 63: 
          { tipo=yytext(); return Interface;
          }
        case 100: break;
        case 34: 
          { tipo=yytext(); return Caso;
          }
        case 101: break;
        case 24: 
          { tipo=yytext(); return Coma;
          }
        case 102: break;
        case 35: 
          { tipo=yytext(); return Nulo;
          }
        case 103: break;
        case 12: 
          { tipo=yytext(); return Suma;
          }
        case 104: break;
        case 64: 
          { tipo=yytext(); return Verdadero;
          }
        case 105: break;
        case 45: 
          { tipo=yytext(); return Hasta;
          }
        case 106: break;
        case 10: 
          { tipo=yytext(); return Parentesis_izq;
          }
        case 107: break;
        case 22: 
          { tipo=yytext(); return Corchete_izq;
          }
        case 108: break;
        case 50: 
          { tipo=yytext(); return Privado;
          }
        case 109: break;
        case 32: 
          { tipo=yytext(); return Mayor_igual;
          }
        case 110: break;
        case 25: 
          { tipo=yytext(); return Punto;
          }
        case 111: break;
        case 9: 
          { tipo=yytext(); return Parentesis_der;
          }
        case 112: break;
        case 23: 
          { tipo=yytext(); return Corchete_der;
          }
        case 113: break;
        case 15: 
          { tipo=yytext(); return Potencia;
          }
        case 114: break;
        case 13: 
          { tipo=yytext(); return Resta;
          }
        case 115: break;
        case 41: 
          { tipo=yytext(); return Nuevo;
          }
        case 116: break;
        case 19: 
          { tipo=yytext(); return Mayor;
          }
        case 117: break;
        case 20: 
          { tipo=yytext(); return Llave_izq;
          }
        case 118: break;
        case 3: 
          { tipo=yytext(); return Valor_numerico;
          }
        case 119: break;
        case 21: 
          { tipo=yytext(); return Llave_der;
          }
        case 120: break;
        case 52: 
          { tipo=yytext(); return Booleano;
          }
        case 121: break;
        case 65: 
          { tipo=yytext(); return Implementa;
          }
        case 122: break;
        case 33: 
          { tipo=yytext(); return Diferente;
          }
        case 123: break;
        case 57: 
          { tipo=yytext(); return Caracter;
          }
        case 124: break;
        case 4: 
          { /*Ignore*/
          }
        case 125: break;
        case 48: 
          { tipo=yytext(); return Cadena;
          }
        case 126: break;
        case 6: 
          { tipo=yytext(); return Y;
          }
        case 127: break;
        case 17: 
          { tipo=yytext(); return Punto_coma;
          }
        case 128: break;
        case 30: 
          { tipo=yytext(); return Igual;
          }
        case 129: break;
        case 54: 
          { tipo=yytext(); return Importar;
          }
        case 130: break;
        case 53: 
          { tipo=yytext(); return Intentar;
          }
        case 131: break;
        case 39: 
          { tipo=yytext(); return Vacio;
          }
        case 132: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
