
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizara;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Estatico = 43;
  public static final int Entero = 37;
  public static final int Y = 60;
  public static final int Nulo = 51;
  public static final int Coma = 22;
  public static final int Intentar = 56;
  public static final int O = 61;
  public static final int Clase = 48;
  public static final int Diferente = 26;
  public static final int Potencia = 11;
  public static final int Llave_izq = 18;
  public static final int Metodo_imprimir = 27;
  public static final int Valor_numerico = 29;
  public static final int Interface = 55;
  public static final int Opcion = 44;
  public static final int Menor = 16;
  public static final int Break = 46;
  public static final int Error = 30;
  public static final int Doble = 38;
  public static final int Parentesis_der = 3;
  public static final int Nuevo = 52;
  public static final int Mayor = 17;
  public static final int Corchete_der = 21;
  public static final int Booleano = 40;
  public static final int Punto = 23;
  public static final int Vacio = 50;
  public static final int Division = 10;
  public static final int Flotante = 39;
  public static final int Cadena = 35;
  public static final int Modulo = 12;
  public static final int Publico = 33;
  public static final int Falso = 2;
  public static final int Asignar = 5;
  public static final int Hacer = 47;
  public static final int EOF = 0;
  public static final int De_otro_modo = 58;
  public static final int Capturar = 57;
  public static final int error = 1;
  public static final int Mayor_igual = 15;
  public static final int Caso = 45;
  public static final int Linea = 31;
  public static final int Llave_der = 19;
  public static final int Comilla_simple = 25;
  public static final int Menor_igual = 14;
  public static final int Privado = 32;
  public static final int Dos_puntos = 24;
  public static final int Implementa = 54;
  public static final int Identificador = 28;
  public static final int Si = 41;
  public static final int Punto_coma = 13;
  public static final int Resta = 8;
  public static final int Protegido = 34;
  public static final int Caracter = 36;
  public static final int Extiende = 53;
  public static final int Mientras = 42;
  public static final int Parentesis_izq = 4;
  public static final int Verdadero = 62;
  public static final int Retorno = 49;
  public static final int Multiplicacion = 9;
  public static final int Corchete_izq = 20;
  public static final int Importar = 59;
  public static final int Suma = 7;
  public static final int Igual = 6;
  public static final int Comillas = 63;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Falso",
  "Parentesis_der",
  "Parentesis_izq",
  "Asignar",
  "Igual",
  "Suma",
  "Resta",
  "Multiplicacion",
  "Division",
  "Potencia",
  "Modulo",
  "Punto_coma",
  "Menor_igual",
  "Mayor_igual",
  "Menor",
  "Mayor",
  "Llave_izq",
  "Llave_der",
  "Corchete_izq",
  "Corchete_der",
  "Coma",
  "Punto",
  "Dos_puntos",
  "Comilla_simple",
  "Diferente",
  "Metodo_imprimir",
  "Identificador",
  "Valor_numerico",
  "Error",
  "Linea",
  "Privado",
  "Publico",
  "Protegido",
  "Cadena",
  "Caracter",
  "Entero",
  "Doble",
  "Flotante",
  "Booleano",
  "Si",
  "Mientras",
  "Estatico",
  "Opcion",
  "Caso",
  "Break",
  "Hacer",
  "Clase",
  "Retorno",
  "Vacio",
  "Nulo",
  "Nuevo",
  "Extiende",
  "Implementa",
  "Interface",
  "Intentar",
  "Capturar",
  "De_otro_modo",
  "Importar",
  "Y",
  "O",
  "Verdadero",
  "Comillas"
  };
}

