
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jan 07 14:38:01 CST 2025
//----------------------------------------------------

package analizara;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Estatico = 66;
  public static final int Entero = 22;
  public static final int Final_2 = 56;
  public static final int Nulo = 61;
  public static final int Coma = 51;
  public static final int Y = 43;
  public static final int Intentar = 13;
  public static final int O = 44;
  public static final int Llave_izq = 48;
  public static final int Diferente = 42;
  public static final int Potencia = 36;
  public static final int Clase = 2;
  public static final int Metodo_imprimir = 65;
  public static final int Valor_numerico = 55;
  public static final int Interface = 64;
  public static final int Menor = 38;
  public static final int Opcion = 19;
  public static final int Break = 16;
  public static final int Error = 57;
  public static final int Parentesis_der = 47;
  public static final int Doble = 23;
  public static final int Nuevo = 67;
  public static final int Corchete_der = 60;
  public static final int Mayor = 37;
  public static final int Booleano = 25;
  public static final int Punto = 52;
  public static final int Continuar = 17;
  public static final int Vacio = 28;
  public static final int Division = 34;
  public static final int Flotante = 24;
  public static final int Cadena = 26;
  public static final int Modulo = 35;
  public static final int Publico = 3;
  public static final int Falso = 30;
  public static final int Asignar = 45;
  public static final int Hacer = 11;
  public static final int EOF = 0;
  public static final int De_otro_modo = 21;
  public static final int Mayor_igual = 39;
  public static final int error = 1;
  public static final int Capturar = 14;
  public static final int Caso = 20;
  public static final int Llave_der = 49;
  public static final int Comilla_simple = 62;
  public static final int Menor_igual = 40;
  public static final int Privado = 4;
  public static final int Dos_puntos = 53;
  public static final int Implementa = 7;
  public static final int Identificador = 54;
  public static final int Si = 8;
  public static final int Punto_coma = 50;
  public static final int Resta = 32;
  public static final int Protegido = 5;
  public static final int Caracter = 27;
  public static final int Sino = 9;
  public static final int Finalmente = 15;
  public static final int Mientras = 10;
  public static final int Extiende = 6;
  public static final int Parentesis_izq = 46;
  public static final int Corchete_izq = 58;
  public static final int Multiplicacion = 33;
  public static final int Verdadero = 29;
  public static final int Retorno = 18;
  public static final int Importar = 59;
  public static final int Hasta = 12;
  public static final int Suma = 31;
  public static final int Igual = 41;
  public static final int Comillas = 63;
}

